// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsdoepptrpgnoyfdvywr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzZG9lcHB0cnBnbm95ZmR2eXdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MzcyNzgsImV4cCI6MjA2MTIxMzI3OH0.vSJuSbv6LBwj1QfEXP8G0Thiyn7p2T-P_iCo6bqqW0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);